# Generated by Django 4.2 on 2023-07-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("phone", models.CharField(max_length=11)),
                ("dsg", models.CharField(max_length=20)),
                ("salary", models.IntegerField()),
                ("city", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=30)),
            ],
        ),
    ]
